/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This is a test for the new ActionSchema definition
 */
export interface ActionSchemaTestSchema {
  /**
   * Variables that the user can set from the UI. These can also be plugin variables.
   */
  variables?: {
    getStuff?: string;
    [k: string]: any;
  };
  /**
   * Items in your grid.
   */
  items?: {
    __id?: string;
    name?: string;
    age?: {
      [k: string]: any;
    };
    [k: string]: any;
  }[];
  [k: string]: any;
}
