/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * To improve ActionSchema we do research based on anonymous usage data. You can opt-out of this by unchecking this box.
 */
export type AnonymousUsageInfoCollection = boolean;
/**
 * The entire OpenAPI URL should be here
 */
export type OpenAPIURL = string;
/**
 * In case this is given and your IS_DEV is set to "true", this URL will be used when executing. However, this URL will never be set into the ActionSchema as this would cause things to not work when pushing to production. This is why it's needed to have this parameter: we want a good development experience at localhost for any openapi we may make, being able to make production-schemas from localhost
 */
export type LocalhostOpenAPIURL = string;
/**
 * Here you can fill in the OpenAPIs you want to use. By default, OpenAPIs in your schema files will also be indexed.
 */
export type OpenAPIs = OpenAPI[];
/**
 * Needed for 'same-site' or 'custom' so your results can be stored.
 */
export type UpstashAPIKey = string;
export type UpstashEmail = string;
/**
 * Needed for 'custom'. Ensure this OpenAPI implements https://demo.actionschema.com/openapi.json
 */
export type ActionSchemaServerOpenAPIPath = string;

export interface LocalStorageState {
  general?: Configuration;
  openApis?: OpenAPIs;
  actionSchemaServer?: ActionSchemaServer;
  [k: string]: any;
}
export interface Configuration {
  isUsageCollected?: AnonymousUsageInfoCollection;
  [k: string]: any;
}
export interface OpenAPI {
  __id?: OpenAPIURL;
  /**
   * Headers
   */
  headers?: {
    [k: string]: string;
  };
  localhostOpenapiUrl?: LocalhostOpenAPIURL;
  [k: string]: any;
}
export interface ActionSchemaServer {
  /**
   * - 'browser' means calculations will happen locally in the browser.
   * - 'same-site' means calculations will happen where ever this frontend is hosted, assuming there is an API available there.
   * - 'custom' allows you to specify a custom host openapi address at which the endpoints should be defined.
   */
  actionSchemaServerLocation?: "browser" | "same-site" | "custom";
  upstashApiKey?: UpstashAPIKey;
  upstashEmail?: UpstashEmail;
  actionSchemaOpenApiPath?: ActionSchemaServerOpenAPIPath;
  /**
   * Headers:
   */
  actionSchemaOpenApiHeaders?: {
    [k: string]: string;
  };
}
