/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * 🎙 Screenless!
 */
export interface PhoneRecordingInboxSchema {
  $schema?: string;
  items?: PhoneRecordingInbox[];
  [k: string]: any;
}
export interface PhoneRecordingInbox {
  /**
   * Id
   */
  __id?: string;
  createdAt?: string;
  item?: string;
  /**
   * check if the value is of type audio
   */
  isAudio?: string;
  /**
   * transcript
   */
  transcript?: string;
  /**
   * transcriptText
   */
  transcriptText?: string;
  /**
   * analysis
   */
  analysis?: string;
  /**
   * analysisTitle
   */
  analysisTitle?: string;
  /**
   * makesSense
   */
  makesSense?: string;
  /**
   * tokenCount
   */
  tokenCount?: string;
  /**
   * statements
   */
  statements?: string;
  sendWhatsapp?: string;
  /**
   * Send mail with attachment
   */
  sendEmail?: string;
  /**
   * callDurationMinutes
   */
  callDurationMinutes?: string;
  /**
   * True if this is a personal message
   */
  personalMessageAnalysis?: string;
  /**
   * isPersonalMessage
   */
  isPersonalMessage?: string;
  /**
   * personalMessageTo
   */
  personalMessageTo?: string;
  /**
   * personalMessageCleaned
   */
  personalMessageCleaned?: string;
  /**
   * personalMessageSubject
   */
  personalMessageSubject?: string;
  /**
   * sendPersonalMessage
   */
  sendPersonalMessage?: string;
  /**
   * isOperatorMentioned
   */
  isOperatorMentioned?: string;
  /**
   * isVisualRequested
   */
  isVisualRequested?: string;
  /**
   * imagePrompts
   */
  imagePrompts?: string;
  /**
   * averageWordConfidence
   */
  averageWordConfidence?: string;
  /**
   * isHighQuality
   */
  isHighQuality?: string;
  /**
   * tweetableStatements
   */
  tweetableStatements?: string;
  /**
   * speakerAmount
   */
  speakerAmount?: string;
  /**
   * If more than 1 speaker... This happens
   */
  hasOtherSpeakers?: string;
  /**
   * isNote
   */
  isNote?: string;
  /**
   * transcriptNote
   */
  transcriptNote?: string;
  /**
   * Analysing the different speakers
   */
  speakersAnalysis?: string;
  /**
   * speakersAnalysisSummary
   */
  speakersAnalysisSummary?: string;
  /**
   * To be filled in by the user or automatically from phonecalls or meetings. Must be selected from the users user-centric relations. Should be string[]
   */
  relationIds?: string[];
  /**
   * finishedAt
   */
  finishedAt?: string;
  /**
   * subtitle
   */
  subtitle?: string;
  /**
   * summary
   */
  summary?: string;
  namedPeopleAndCompanies?: string;
  uncertainWordPercentage?: string;
  /**
   * analysisKeywords
   */
  analysisKeywords?: string;
  /**
   * transcriptHtml
   */
  transcriptHtml?: string;
  /**
   * deleteIfNeeded
   */
  deleteIfNeeded?: string;
  attachmentName?: string;
  /**
   * transcript2
   */
  transcript2?: string;
  /**
   * cleanTranscriptText
   */
  cleanTranscriptText?: string;
  extensiveSummary?: string;
  outline?: string;
  /**
   * outlineHtml
   */
  outlineHtml?: string;
  /**
   * extensiveSummaryHtml
   */
  extensiveSummaryHtml?: string;
  /**
   * emailHtml
   */
  emailHtml?: string;
  suggestedActions?: string;
  /**
   * suggestedGpts
   */
  suggestedGpts?: string;
  /**
   * suggestedActionsHtml
   */
  suggestedActionsHtml?: string;
  /**
   * Something that was said before the call
   */
  prompt?: string;
  /**
   * If speaker-amount is 1, it's deemed a personal note.
   */
  isPersonalNote?: string;
  /**
   * sendWebhook
   */
  sendWebhook?: string;
  [k: string]: any;
}
