/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Keys should be OpenAPI Urls, values could be private proxy settings for this openapi server
 */
export interface SecuritySchema {
  [k: string]: {
    security?: SecurityRequirement;
  };
}
export interface SecurityRequirement {
  [k: string]: string[];
}
